<?php
/**
 * @file
 * 
 * Module for providing a service for logging in users, register users, logging off users
 * 
 */

 /**
  * Function converter_etc_server
  * 
  * Creates a SOAP WebService Instance
  */
function converter_etc_server()
{	 
	$path_funciones = getcwd() . '/' . drupal_get_path('module', 'converter_etc') . '/includes/wserver_converter.inc';
	
	include_once($path_funciones);
	
	//include wsdl file
	$path_wsdl = getcwd() . '/' . drupal_get_path('module', 'converter_etc') . '/wsdl/converter.wsdl';
	
	//create a SoapServer object
	$server = new SoapServer($path_wsdl);
 
 	//adding the methods
 	$server->addFunction("existeUsuario");
 	$server->addFunction("crearUsuario");
 	$server->addFunction("actualizarUsuario");
 	$server->addFunction("logOut7");
 	$server->addFunction("logIn7");
 	$server->addFunction("getSessionName");
 	$server->addFunction("isLogged");
 	$server->addFunction("buildCookie");
 	$server->handle();
}

 
 /**
  * Implements hook_menu()
  */
 function converter_etc_menu()
 {
	$items = array();

	//define the menu item for the webservice endpoint
	$items['services/soap'] = array(
		'title' => 'SOAP Server',
		'page callback' => 'converter_etc_server',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
 	);

    return $items;
}


/**
 * Implements hook_user_presave()
 * 
 * A user account is about to be created or updated. This function is called in these situations:
 * 
 * 1. an user is being created in Drupal 7 from user/register
 * 2. an user is being created in Drupal 7 from the Drupal 6 webservice methods.
 */
 function converter_etc_user_presave(&$edit, $account, $category)
 {
 	if ($account->is_new){ 
		// user/register form submission from Drupal 7
 		if (isset($_POST["name"])){ 
 			//Drupal 6 webservice instance
		 	$client = new SoapClient("http://clasificados.eltiempo.com/sites/all/modules/custom/esinergia_exporter/wsdl/exporter.wsdl");
		
			$language = "LANGUAGE_NONE";
		
			$usuario = $_POST["name"];
			$correo = $edit["mail"];
			$contra = $_POST["pass"]["pass1"];
			$nombre = $edit["field_user_name"][$language][0]["value"];
			$apellido = $edit["field_user_last"][$language][0]["value"];
			$tipodoc = $edit["field_id_type"][$language][0]["tid"];
			$numdoc = $edit["field_id_number"][$language][0]["value"];
		 	$telefono = $edit["field_phone_number"][$language][0]["value"];
		  	
		  	//calling the webservice method for creating the user in Drupal 6
		  	$tmp = $client->crearUsuario($correo, $usuario, $contra, $nombre, $apellido, $telefono, $tipodoc, $numdoc);
		  	
		  	$res = json_decode($tmp);
		  	
		  	if (!$res){
		  		//error creating the user in Drupal 6
		  	} else {
		  		//user created in Drupal 6
		  		//save the Drupal 6 user id inside a field in Drupal 7, because they are different
				$edit["field_uid_d6"][$language][0]["value"] = $res->msg;
		  	}
	  	
 		}
 	}
 }
 