<?php
/**
 * @file
 *
 * Webservice Creation
 *
 * Version 1.0 - 10/02/2014
 * - Initial version
 *
 * Version 1.1 - 20/02/2014
 * - hook esinergia_auth_user() Bugfixes.
 *
 * Version 1.5 - 20/03/2014
 *  - Security Settings
 *
 * Version 1.7 - 23/03/2014
 *  - New Logging Off Method
 *
 * Version 1.8 - 02/07/2014
 * - logIn Definition
 *
 * Version 1.9 - 06/07/2014
 * - resetPasswd Definition
 * - registerUser Definition
 */

 /**
  * Function esinergia_auth_server
  *
  * Menu callback for creating a SOAP webservice instance
  */
function esinergia_auth_server()
{
	$path_funciones = getcwd() . '/' . drupal_get_path('module', 'esinergia_auth') . '/includes/wserver_auth.inc';

	include_once($path_funciones);

	//include wsdl file
	$path_wsdl = getcwd() . '/' . drupal_get_path('module', 'esinergia_auth') . '/wsdl/auth.wsdl';

	//create a SoapService Object
	$server = new SoapServer($path_wsdl);

 	//adding the available methods
 	$server->addFunction("isLogged");
 	$server->addFunction("getUid");
 	$server->addFunction("getUserName");
 	$server->addFunction("logOut");
 	$server->addFunction("logIn");
 	$server->addFunction("resetPasswd");
 	$server->addFunction("registerUser");
 	$server->handle();
}

 /**
  * Implements hook_menu
  */
 function esinergia_auth_menu()
 {
	$items = array();

	//define the menu item for the webservice endpoint
	$items['services/soap2'] = array(
		'title' => 'SOAP Server',
		'page callback' => 'esinergia_auth_server',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
 	);

    return $items;
}
