<?php
/**
 * @file
 *
 * Module for providing auth services for Drupal 7, cookie creation and session purging.
 */

 /**
  * Implements hook_user_login
  *
  * If user logs in Drupal 7, this hook will call the webservice for logging in Drupal 6
  */
 function logincookie_etc_user_login(&$edit, $account)
 {
 	global $user;
 	global $cookie_domain;

 	//if $edit['input'] is set, it means that the user is logging in from the login page (/user)
 	if (isset($edit['input'])){ 
 		//user and pass
	 	$usuario = $edit['input']['name'];
	 	$contrasena = $edit['input']['pass'];

	 	//session variable for storing the SID from Drupal 6
	 	$_SESSION["sid_usuario_d6"] = "";

	 	//call to Drupal 6 SOAP webservice
	 	$client = new SoapClient("http://clasificados.eltiempo.com/sites/all/modules/custom/esinergia_exporter/wsdl/exporter.wsdl");

	 	//check if user in Drupal 7 exists in Drupal 6 as well
	 	$res = $client->existeUsuario($usuario);

	 	$tmp = json_decode($res);

	 	if (!$tmp->codigo){
	 		//user doesn't exist in Drupal 6
	 	} else {
	 		if (is_array($contrasena)){
	 			//user just joined/registered into the website
	 			$contrasena = $edit['input']['pass']['pass2'];
	 		}

	 		//logs in Drupal 6
	 		$res = $client->logIn($usuario, $contrasena);

	 		$tmp = json_decode($res);

	 		if ($tmp->codigo  == -1){
	 			//user doesn't exist in Drupal 6
	 		} else if ($tmp->codigo == 0){
	 			//wrong user/password credentials
	 		} else {
	 			//get session name from Drupal 6
			 	$session_name = $client->getSessionName();

			 	//no construyo bien la cookie en el primer intento de logIn, forzar login de nuevo y la construccion de la cookie
			 	//sometimes the first call to the logIn method wasn't working, so we make another call to logIn for generating the cookie
			 	if (!isset($tmp->sid)){
			 		$res1 = $client->logIn($usuario, $contrasena);

			 		$tmp1 = json_decode($res1);

			 		//buildCookie method returns the SID from Drupal 6
			 		$res2 = $client->buildCookie($tmp1->uid, $tmp1->timestamp);

			 		$tmp2 = json_decode($res2);
			 	} else { 
			 		//buildCookie method returns the SID from Drupal 6
			 		$res = $client->buildCookie($tmp->uid, $tmp->timestamp);

			 		$tmp2 = json_decode($res);

			 	}

			 	//build the Druoal 6 cookie 
			 	setcookie($session_name, $tmp2->sid, $_SERVER['REQUEST_TIME'] + 3600, "/", ".eltiempo.com");

			 	//store the Drupal 6 SID into the session variable
			 	$_SESSION["sid_usuario_d6"] = $tmp2->sid;
	 		}
	 	}

 	} else {
 		//extra validations
 	}
 }

 /**
  * Implements hook_user_logout
  *
  * If the user logs out from Drupal 7, this hook will call the webservice method logOut for logging out from Drupal 6 as well
  */
 function logincookie_etc_user_logout($account)
 {
 	$client = new SoapClient("http://clasificados.eltiempo.com/sites/all/modules/custom/esinergia_exporter/wsdl/exporter.wsdl");

 	$session_name = $client->getSessionName();

 	//Drupal 6 SID
 	$sid_d6 = $_SESSION["sid_usuario_d6"];

 	if ($sid_d6 != ""){
 		//logs out from Drupal 6, passing the Drupal 6 SID as argument
 		$client->logOut($sid_d6);
 	} else {
 		//just in case the user logged in from the Mobile page
 		$client->logOut($_COOKIE[$session_name]);
 	}
 }
